extmod/asyncio: Make SingletonGenerator create_task()-aware.
This commit allows the awaitable returned by asyncio.sleep/sleep_ms()
to be passed directly to asyncio.create_task().

Although the documentation says that sleep/sleep_ms() are coroutines and
create_task() accepts coroutines, this is not the case; sleep/sleep_ms()
actually return a SingletonGenerator(), which is missing a send() method.

> === import asyncio
> === asyncio.run(asyncio.sleep_ms(2000))
> ===
> Traceback (most recent call last):
>   File "<stdin>", line 3, in <module>
>   File "asyncio/core.py", line 1, in run
>   File "asyncio/core.py", line 1, in create_task
> TypeError: coroutine expected

This is easily solved by implementing the missing send() method such as:

> === import asyncio
> === from time import ticks_ms as ticks, ticks_add
> ===
> === class SingletonGenerator2(asyncio.SingletonGenerator):
> ===   def send(self, x):
> ===     self.__next__()
> ===
> === def sleep_ms(t, sgen=SingletonGenerator2()):
> ===   sgen.state = ticks_add(ticks(), max(0, t))
> ===   return sgen
> ===
> === asyncio.run(sleep_ms(2000))
> ===
> >>>

Signed-off-by: Takayuki 'January June' Suwa <jjsuwa_sys3175@yahoo.co.jp>