tools/pydfu: Add support for USB serial number argument.
In automated testing platforms that use multiple Micropython devices and
run within CI/CD pipelines, there can be cases where two or more devices
are left in DFU mode, causing the pydfu flashing process to fail with
the following error:

...pydfu.py", line 117, in init
    raise ValueError("Multiple DFU devices found")
ValueError: Multiple DFU devices found

To allow distinguishing between DFU devices a serial number argument was
added. It can be retrieved using the dmesg:

...
usb 1-7.3: Product: STM32  BOOTLOADER
usb 1-7.3: Manufacturer: STMicroelectronics
usb 1-7.3: SerialNumber: 315C34853133

The serial number should be passed as is, for example:

./pydfu.py -u firmware.dfu --serial 315C34853133

With the serial number argument, users and CI/CD pipelines can now flash
specific devices, even when multiple DFU devices are present.

Signed-off-by: Ilya Orazov <ilordash02@gmail.com>