tests/basics requires python3.3
tests/bytecode/run-tests already uses puthon3.3, so let's just use it here
too.

Fore reference, errors with python 3.2.3:

  File "tests/generator1.py", line 12
    return None
SyntaxError: 'return' with argument inside generator

  File "tests/list_clear.py", line 3, in <module>
    x.clear()
AttributeError: 'list' object has no attribute 'clear'

etc.