py/asmarm: use __builtin___clear_cache instead of __clear_cache
__clear_cache causes compiler error when using clang.

../py/asmarm.c:46:2: error: implicit declaration of function '__clear_cache' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
        __clear_cache(start, end);
        ^

Also replace tabs with spaces.