tools/mpremote: Fix fs_stat exception with namedtuples.
Fixes exception when doing "mpremote cp file :"
or "mpremote mip install os-path", when
os.stat() returns stat_result namedtuple instead of plain tuple.

This is the case if one has done "mip install os-path"
Ref https://github.com/micropython/micropython-lib/commit/f4cfc3c71a5e5ba56df586f8aecb833d8ab51269

Example exception:

    ValueError: malformed node or string on line 1:
     Call(func=Name(id='stat_result', ctx=Load()), args=[],
     keywords=[keyword(arg='st_mode',
       value=Constant(value=16384, kind=None)), ...
     keyword(arg='st_ctime', value=Constant(value=0, kind=None))])

Issue found by @snowkoli

Signed-off-by: Jon Nordby <jononor@gmail.com>