Refine error message for rp2040 audiobusio I2S object creation
The error message for creating an I2S object on the rp2040 platform
in CircuitPython can be misleading when the word_select and data pins
are not sequential. This change updates the error message to provide
clearer guidance by specifying "GPIO pins" instead of just "pins".
The revised message now reads:

ValueError: Bit clock and word select must be sequential GPIO pins

Closes #8058

Signed-off-by: Sumitra Sharma <sumitraartsy@gmail.com>