py: Fix compilation of persistentcode with uncommon configs
With the following configuration:

    #define MICROPY_PERSISTENT_CODE_SAVE (1)
    #define MICROPY_PERSISTENT_CODE_LOAD (1)

The code fails to compile:

    persistentcode.c: In function 'load_raw_code':
    persistentcode.c:457:13: error: 'n_obj' undeclared
             n_obj, n_raw_code,

If MICROPY_EMIT_NATIVE disabled, there are more errors due to the use of
undefined fields in mp_raw_code_t.

This patch fixes compilation by avoiding undefined fields.

MICROPY_EMIT_NATIVE was changed to MICROPY_EMIT_ANY_ASM in this file to
match mp_raw_code_t definition.