Fix compile errors caused by casting from a byte to a pointer.
In particular, I was seeing these errors:

../py/objstr.c: In function ‘str_binary_op’:
../py/objstr.c:80:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
../py/objstr.c: In function ‘bytes_it_iternext’:
../py/objstr.c:552:26: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]

when compiling unix on a 64-bit platform (I don't have a convenient 32-bit platform).