esp8266/fatfs: Remove spi_flash.h, fixed compilation process.
Compilation process fixed. IOCTL enabled again, was
causing strange issue with esptool.py:

Create build/firmware-combined.bin
Traceback (most recent call last):
  File "/home/march/wa/esp/esp-open-sdk/xtensa-lx106-elf/bin/esptool.py", line 647, in <module>
    image.add_segment(e.get_symbol_addr(start), data)
  File "/home/march/wa/esp/esp-open-sdk/xtensa-lx106-elf/bin/esptool.py", line 384, in get_symbol_addr
    self._fetch_symbols()
  File "/home/march/wa/esp/esp-open-sdk/xtensa-lx106-elf/bin/esptool.py", line 381, in _fetch_symbols
    self.symbols[fields[2]] = int(fields[0], 16)
ValueError: invalid literal for int() with base 16: 'U'