esp32: (cleanup) Replace exception raising with the corresponding utility function
  - Changed: ValueError, TypeError, NotImplementedError
  - OSError invocations unchanged, because the corresponding utility
    function takes ints, not strings like the long form invocation.
  - OverflowError, IndexError and RuntimeError also not changed for now
    because of "implicit declaration of function"