Bump setuptools version
Building locally I saw this message:
```
/home/jepler/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/setuptools_scm/integration.py:27: RuntimeWarning:
ERROR: setuptools==44.1.1 is used in combination with setuptools_scm>=6.x

Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=45
```

For some reason this dependency is not automatically met, e.g., by
setuptools_scm specifying a versioned dependency itself! So specify
it here.