Update eth_phy include : Typo in line 29.
Typo on line 29 (PYH instead of PHY).

Compilation failing, here is the output:

```
eth_phy.h:28: error: header guard 'MICROPY_INCLUDED_STM32_PHY_H' followed
by '#define' of a different macro [Werror=header-guard]
    28 | #ifndef MICROPY_INCLUDED_STM32_PHY_H
eth_phy.h:29: note: 'MICROPY_INCLUDED_STM32_PYH_H' is defined here;
did you mean 'MICROPY_INCLUDED_STM32_PHY_H'?
    29 | #define MICROPY_INCLUDED_STM32_PYH_H
```

Typo on line 29 (PYH instead of PHY) fixed.

Signed-off-by: Tico06 <e.grammatico@gmail.com>