Unconditionally use sphinx_rtd_theme when building docs
This is a speculative fix for the latest build failure on RTD,
https://readthedocs.org/projects/circuitpython/builds/21689508/
which appears to be due to a change in RTD's "conf.py.tmpl"

https://github.com/readthedocs/readthedocs.org/commit/2066e3486a25bbd76431e1f8c20be3da0043f03a

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/circuitpython/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 358, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/circuitpython/checkouts/latest/conf.py", line 600, in <module>
    'html_theme': html_theme,
                  ^^^^^^^^^^
NameError: name 'html_theme' is not defined
```