build.yml: Fix building mpy-cross-mac
Recently, the macos-10.15 image was updated with a non-brew version of awscli.  This made our CI script, which does a `brew install awscli` fail:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/aws
Target /usr/local/bin/aws
already exists. You may want to remove it:
  rm '/usr/local/bin/aws'
```