Update the pico-sdk submodule to ensure that all RP2350 board headers explicitly define PICO_RP2350A This commit updates the pico-sdk submodule to commit c88bd53, which provides critical fixes for RP2350 board header definitions.
Key changes in this specific pico-sdk version:
- Ensure all RP2350 board-headers explicitly define PICO_RP2350A
- Fixes board detection and configuration for RP2350 variants
- Improves compatibility with RP2350A and RP2350B chip variants

MicroPython v1.26.1 on 2025-09-11;     Seeed XIAO RP2350 with RP2350

Use the firmware in this interface XIAO_RP2350
Use the following test code：

Using my new compiled firmware：

```
>>> import machine
>>> machine.ADC(4).read_u16()

13955
```

Observed behaviour：

```
>>> import machine
>>> machine.ADC(29).read_u16()

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: Pin doesn't have ADC capabilities
>>>
```

The reason is that pico-sdk is not the latest.

The ADC function modified the judgment logic after this submission, and changed the range of the ADC pin to be specified by macro(ADC_BASE_PIN and NUM_ADC_CHANNELS).
See: https://github.com/micropython/micropython/commit/34e463d861c5ebb33ec317749a008d461616cfbc

These two macros were not used in pico-sdk until after this commit.
See: https://github.com/raspberrypi/pico-sdk/commit/c88bd53a68fe2199fa4a5e6473ba88278f339a2b

The following file is the xiao rp2350 header file in the pico-sdk used by the current version of micropython. This file does not include the changes submitted above.
See: https://github.com/raspberrypi/pico-sdk/blob/9a4113fbbae65ee82d8cd6537963bc3d3b14bcca/src/boards/include/boards/seeed_xiao_rp2350.h

Please adopt pico-sdk with RP2350A defined in header files