Bugfix AttributeError in ESP8266 _boot.py if flash not formatted
The current _boot.py for ESP8266 does `except OSError` but if flash
filesystem is not formatted, this Traceback will happen:

```
  File "_boot.py", line 8, in <module>
AttributeError: 'FlashBdev' object has no attribute 'mount'
```

Also it's not needed to try the mount if `flashbdev.bdev` is None.