tests/thread/thread_stacksize1.py: increase stack size for cpython
On arm64

  >>> _thread.stack_size(32*1024)
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ValueError: size not valid: 32768 bytes

Increase to 512k since on modern Linux, the default stack size is usually 8MB.