lib/libm_dbl: Allow building when DBL_EPSILON is defined in <float.h>.
This is the case in arm-none-eabi-gcc 14.2.1 (debian trixie).

This fixes a diagnostic like:

    ../../lib/libm_dbl/libm.h:92:9: error:
        "DBL_EPSILON" redefined [-Werror]
    /usr/lib/gcc/arm-none-eabi/14.2.1/include/float.h:114:9: note:
        this is the location of the previous definition

when building MPS2_AN500 (qemu port).

Signed-off-by: Jeff Epler <jepler@unpythonic.net>